version: 2
jobs:
   build:
     docker:
       - image: circleci/golang:1.11
     working_directory: /home/circleci/.go_workspace/src/github.com/r3labs/diff
     steps:
       - checkout
       - run:
           name: Unit Tests
           command: make test
